### ISSUE TITLE
Changes do not get applied when using with webpack watch

### ISSUE THREAD

**Issue by kinyat** [epegzz/sass-vars-loader#15]
Currently if you use webpack to watch files, when there are any changes in the javascript which `sass-vars-loader` is used, it will not tigger the rebuild or when it is triggered, it still return the old values.

I am wondering if this is something `sass-vars-loader` can handle so that webpack watch can work properly.

Many thanks.

**Comment by lginq** [comment]
Any idea how we can make .js file populate dynamically from the UI?

**Comment by lginq** [comment]
any update on this?

**Comment by epegzz** [comment]
I don't think that is possible unfortunately :-(
Loaders don't have much control over the compiler. I guess only a plugin would be able to achieve that.

**Comment by epegzz** [comment]
Good news! I've been looking deeper into it, and it turned out that it is possible to make webpack watch for changes in the referenced files. Now working with version 2.2.0 👍
