### ISSUE TITLE
Where to place sassVars with multiple loaders?

### ISSUE THREAD

**Issue by ncphillips** [epegzz/sass-vars-loader#2]
The variables that I'm declaring in sassVars do not seem to be getting injected.

It just says "Undefined Variable"

Here is a part of my webpack config.

```javascript
 module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      },
      {
        test   : /\.css$/,
        loaders: ['style', 'css', 'resolve-url']
      },
      {
        test: /\.scss$/,
        loaders: ['style', 'css', '@epegzz/sass-vars-loader', 'resolve-url', 'sass?sourceMap'],

      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /\.(woff2?|ttf|svg|eot|jpe?g)$/,
        loader: 'ignore-loader'
      },
    ],
  },
  sassVars: {
    vars: {
      favouriteColor: 'red',
    }
  },
```

**Comment by epegzz** [comment]
Hey :)

You got the order wrong. `sass-vars-loader` needs come after `sass`:

```javascript
 module: {  
      {
        test: /\.scss$/,
        loaders: ['style', 'css', 'resolve-url', 'sass?sourceMap', '@epegzz/sass-vars-loader'],

      },
    ],
  },
  sassVars: {
    vars: {
      favouriteColor: 'red',
    }
  },
```

**Comment by ncphillips** [comment]
I'm still getting the `Undefined Variable` error, but there's also this new error:

```
main.scss:4Uncaught Error: Cannot find module "!!./../../node_modules/css-loader/index.js!./../../node_modules/resolve-url-loader/index.js!./../../node_modules/sass-loader/index.js?sourceMap!./../../node_modules/@epegzz/sass-vars-loader/index.js!./main.scss"
```

**Comment by epegzz** [comment]
Can you try and see what happens if you remove the `resolve-url`? `sass-vars-loader` does not use source maps at this point and thus might break `resolve-url` which relies on it. I will look into implementing source-map support as soon as possible.

**Comment by ncphillips** [comment]
Hmmm, I removed `resolve-url` and switched to just `sass`, but I'm still getting the same error.

**Comment by epegzz** [comment]
Okay, let's see
- which version of webpack are you using? (I did not test with version 2 yet)
- did you install `sass-vars-loader` locally?
- are you running it in docker?

**Comment by ncphillips** [comment]
Hey again! 

I'm using `webpack 1.13.2`, it is installed locally, and i am not running in docker

**Comment by epegzz** [comment]
Looks like #5 will fix the issue! Expect a fixed npm version tomorrow :)

**Comment by epegzz** [comment]
resolved in current version on npm
