### ISSUE TITLE
webpack2 compatibility

### ISSUE THREAD

**Issue by epegzz** [epegzz/sass-vars-loader#3]
webpack2 does not allow custom properties

thx @IAMtheIAM for pointing this out!

**Comment by IAMtheIAM** [comment]
You're welcome :-)

**Comment by Milewski** [comment]
how do i use this with ExtractTextPlugin? any ideas?

**Comment by mooror** [comment]
I'm pretty new to webpack 2 but wouldn't it be possible to pass the custom properties in using webpacks new option object? I have seen a couple of old webpack plugins start doing something like this:
```
...
use: [
          {
            loader: 'example-loader',
            options: {
              name: 'value'
            }
          }
        ]
...
```

**Comment by Milewski** [comment]
no.. because at this exactly line [index.js#L11](https://github.com/epegzz/sass-vars-loader/blob/master/index.js#L11) it's not doing so... it should be doing this instead:

```
const config = loaderUtils.getOptions(this) || {};
```

**Comment by mooror** [comment]
After I had posted the above comment I was searching around for a webpack 2 solution and found `[node-sass-json-importer](https://github.com/Updater/node-sass-json-importer)`. It works great.

**Comment by epegzz** [comment]
I updated the Readme for webpack2 :)

**Comment by epegzz** [comment]
@Milewski also added section how to use with ExtractTextPlugin.
