### ISSUE TITLE
HRM doesn't work for variable files in symlinks or packages

### ISSUE THREAD

**Issue by franciscolourenco** [epegzz/sass-vars-loader#34]
Not sure if this is because of the symlinked package, or just because it is from inside node_modules.

Reproduction: 
https://github.com/reproducing/reproduce-sass-var-loader

**Comment by epegzz** [comment]
Thanks for the excellent reproduction repo @franciscolourenco! :)
The issue is now solved, v4.4.0 released to NPM

**Comment by epegzz** [comment]
Or directly use `v5.0.0` :)

**Comment by franciscolourenco** [comment]
Thank you for the prompt fix :)
