### ISSUE TITLE
Compatibility with Webpack HMR (Hot Module Replacement)

### ISSUE THREAD

**Issue by IAMtheIAM** [epegzz/sass-vars-loader#4]
Hey again, it seems that when updating the values in a .js or .json file, webpack-dev-server triggers the incremental recompile, but Hot Module Replacement doesn't kick in and update the module with the new .scss.

Is it compatible with HMR? It's not a major need, rather  cool to have feature. Just wondering.

**Comment by epegzz** [comment]
Hmm, to be honest I have no idea. HMR has always been a bit shaky for me, therefore I stopped using it.

**Comment by IAMtheIAM** [comment]
OK, I'll close the issue.

**Comment by lginq** [comment]
@IAMtheIAM have you got this working?

**Comment by IAMtheIAM** [comment]
No, it still does not work. Unfortunately.

**Comment by lginq** [comment]
@IAMtheIAM any workaround solution?

**Comment by epegzz** [comment]
Should be working now with v2.2.0 :)
