### ISSUE TITLE
Passing transformer function as option

### ISSUE THREAD

**Issue by Ibrahimrahhal** [epegzz/sass-vars-loader#46]
I have a situation where I want to read the variable from a global JSON file & I want the file to be watched as well. I think it would be great if we could have a function to passed as option that will transform the JSON content to something the loader could handle

**Comment by epegzz** [comment]
Hey @Ibrahimrahhal 👋 

I currently don't have the time to maintain or improve this project.
However, feel free to fork or submit a PR 🙂

**Comment by Ibrahimrahhal** [comment]
@epegzz Hey, PR is submitted. Please check it when you have the time

**Comment by dsc8x** [comment]
Thanks! 🙌

Just released `v6.1.0` that includes your changes 👍
