### ISSUE TITLE
npm module not found

### ISSUE THREAD

**Issue by 534N** [epegzz/sass-vars-loader#6]
I tried to do npm install, but got this: 

```
npm ERR! Invalid name: "@epegzz/sass-vars-loader"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/SeanYang/workspace/video-discovery-web/npm-debug.log
➜  video-discovery-web git:(re-branding) ✗ npm install @epegzz/sass-vars-loader
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@epegzz/sass-vars-loader"
npm ERR! node v6.5.0
npm ERR! npm  v2.14.7

npm ERR! Invalid name: "@epegzz/sass-vars-loader"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by epegzz** [comment]
Hey Sean,

npm version 2 does not support scoped packages. If you upgrade your npm to version 3 it should install just fine :)

**Comment by 534N** [comment]
Thx Daniel! I figured it was something to do with npm, your answer came in just as I was trying to upgrade npm, thx!

**Comment by 534N** [comment]
@epegzz Also, I see you are requiring `fs`, which is native in node, meaning you really don't need to do that.... I don't know why it is not causing issue here, but I was having build problem complaining module doesn't exist with another package
